Static linking with latest ffmpeg fails with link errors
Static linking with latest ffmpeg gives the following error: 
  avdevice.lib(dshow.o) : error LNK2001: unresolved external symbol IID_IBaseFilter
          avdevice.lib(dshow_filter.o) : error LNK2001: unresolved external symbol IID_IBaseFilter
 <snip>          
 fatal error LNK1120: 32 unresolved externals

Adding the missing libraries to fix it